version: '3.8'

services:
  app:
    image: juliodevel/myportfolio:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/myportfolio
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - portfolio-network
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=myportfolio
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  portfolio-network:
    driver: bridge 